spring:
  application:
    name: chicken-farm

messengerservice:
  from: ${THREEMA_FROM:huehnerstall}
  to: ${THREEMA_TO:myself}
  secret: ${THREEMA_SECRET:joshua}
  enabled: ${MESSENGER_ENABLED:false}

schedulerservice:
  fixedRate: ${SCHEDULER_FIXED_RATE:60000}
