spring:
  application:
    name: chicken-farm

messengerservice:
  channel: ${SLACK_CHANNEL:c01234567}
  token: ${SLACK_TOKEN:myself}
  enabled: ${MESSENGER_ENABLED:false}

schedulerservice:
  observer:
    cron: "0 * * * * *"
  tare:
    cron: "30 0 5 * * *"

mqtt:
  user: ${MQTT_USER}
  password: ${MQTT_PASSWORD}
  clientId:
    producer: RasPiProducer
    consumer: RasPiConsumer

logging:
  file:
    name: /logs/application-debug.log
  logback:
    rollingpolicy:
      max-history: 14
