spring:
  application:
    name: chicken-farm

messengerservice:
  channel: ${SLACK_CHANNEL:c01234567}
  token: ${SLACK_TOKEN:myself}
  enabled: ${MESSENGER_ENABLED:false}

schedulerservice:
  fixedRate: ${SCHEDULER_FIXED_RATE:60000}
